set -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB"

# Move to another panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Preserve current path
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Equal pane sizes
bind = select-layout tiled

# Synchronize all pances
bind y set-window-option synchronize-panes

# Page up/down with Option+Arrow while in copy mode (scroll)
bind-key -T copy-mode M-Up send-keys -X page-up
bind-key -T copy-mode M-Down send-keys -X page-down
bind-key -T copy-mode-vi M-Up send-keys -X page-up
bind-key -T copy-mode-vi M-Down send-keys -X page-down
